Composite-MLKEM-2025
      { iso(1) identified-organization(3) dod(6) internet(1) 
        security(5) mechanisms(5) pkix(7) id-mod(0) 
        id-mod-composite-mlkem-2025(TBDMOD) }

DEFINITIONS IMPLICIT TAGS ::= BEGIN

EXPORTS ALL;

IMPORTS

PUBLIC-KEY, AlgorithmIdentifier{}, SMIME-CAPS
  FROM AlgorithmInformation-2009  -- RFC 5912 [X509ASN1]
      { iso(1) identified-organization(3) dod(6) internet(1)
        security(5) mechanisms(5) pkix(7) id-mod(0)
        id-mod-algorithmInformation-02(58) }

KEM-ALGORITHM
  FROM KEMAlgorithmInformation-2023
      { iso(1) identified-organization(3) dod(6) internet(1)
        security(5) mechanisms(5) pkix(7) id-mod(0)
        id-mod-kemAlgorithmInformation-2023(109) }
;


--
-- Object Identifiers
--

-- Defined in ITU-T X.690
der OBJECT IDENTIFIER ::=
  {joint-iso-itu-t asn1(1) ber-derived(2) distinguished-encoding(1)}


--
-- Information Object Classes
--

pk-CompositeKEM {OBJECT IDENTIFIER:id}
  PUBLIC-KEY ::= {
    IDENTIFIER id
    KEY BIT STRING
    PARAMS ARE absent
    CERT-KEY-USAGE { keyEncipherment }
  }

kema-CompositeKEM {
  OBJECT IDENTIFIER:id,
    PUBLIC-KEY:publicKeyType }
    KEM-ALGORITHM ::= {
         IDENTIFIER id
         VALUE OCTET STRING
         PARAMS ARE absent
         PUBLIC-KEYS { publicKeyType }
         SMIME-CAPS { IDENTIFIED BY id }
        }



--
-- Composite KEM Algorithms
--


-- TODO: OID to be replaced by IANA
id-MLKEM768-RSA2048-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 30 }

pk-MLKEM768-RSA2048-HKDF-SHA256 PUBLIC-KEY ::= 
  pk-CompositeKEM { 
    id-MLKEM768-RSA2048-HKDF-SHA256 }

kema-MLKEM768-RSA2048-HKDF-SHA256 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM768-RSA2048-HKDF-SHA256, 
      pk-MLKEM768-RSA2048-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM768-RSA3072-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 31 }

pk-MLKEM768-RSA3072 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-RSA3072-HKDF-SHA256 }

kema-MLKEM768-RSA3072-HKDF-SHA256 KEM-ALGORITHM ::=
    kema-CompositeKEM{
      id-MLKEM768-RSA3072-HKDF-SHA256, 
      pk-MLKEM768-RSA3072-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM768-RSA4096-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 32 }

pk-MLKEM768-RSA4096-HKDF-SHA256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-RSA4096-HKDF-SHA256 }

kema-MLKEM768-RSA4096 KEM-ALGORITHM ::=
    kema-CompositeKEM{
      id-MLKEM768-RSA4096-HKDF-SHA256, 
      pk-MLKEM768-RSA4096-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM768-X25519-SHA3-256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1)
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 33 }

pk-MLKEM768-X25519-SHA3-256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-X25519-SHA3-256 }

kema-MLKEM768-X25519-SHA3-256 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM768-X25519-SHA3-256, 
      pk-MLKEM768-X25519-SHA3-256 }


-- TODO: OID to be replaced by IANA
id-MLKEM768-ECDH-P256-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 34 }

pk-MLKEM768-ECDH-P256-HKDF-SHA256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-ECDH-P256-HKDF-SHA256 }

kema-MLKEM768-ECDH-P256-HKDF-SHA256 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM768-ECDH-P256-HKDF-SHA256, 
      pk-MLKEM768-ECDH-P256-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM768-ECDH-P384-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 35 }

pk-MLKEM768-ECDH-P384-HKDF-SHA256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-ECDH-P384-HKDF-SHA256 }

kema-MLKEM768-ECDH-P384-HKDF-SHA256 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM768-ECDH-P384-HKDF-SHA256, 
      pk-MLKEM768-ECDH-P384-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 36 }

pk-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256 }

kema-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256, 
      pk-MLKEM768-ECDH-brainpoolP256r1-HKDF-SHA256 }



-- TODO: OID to be replaced by IANA
id-MLKEM1024-ECDH-P384-HKDF-SHA384 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1)
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 37 }

pk-MLKEM1024-ECDH-P384-HKDF-SHA384 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM1024-ECDH-P384-HKDF-SHA384 }

kema-MLKEM1024-ECDH-P384-HKDF-SHA384 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM1024-ECDH-P384-HKDF-SHA384, 
      pk-MLKEM1024-ECDH-P384-HKDF-SHA384 }


-- TODO: OID to be replaced by IANA
id-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 38 }

pk-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384 PUBLIC-KEY ::= 
  pk-CompositeKEM{
    id-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384 }

kema-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384, 
      pk-MLKEM1024-ECDH-brainpoolP384r1-HKDF-SHA384 }
      

-- TODO: OID to be replaced by IANA
id-MLKEM1024-X448-SHA3-256 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1) 
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 39 }

pk-MLKEM1024-X448-SHA3-256 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM1024-X448-SHA3-256 }

kema-MLKEM1024-X448 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM1024-X448-SHA3-256, 
      pk-MLKEM1024-X448-SHA3-256 }


-- TODO: OID to be replaced by IANA
id-MLKEM1024-ECDH-P521-HKDF-SHA384 OBJECT IDENTIFIER ::= {
  joint-iso-itu-t(2) country(16) us(840) organization(1)
  entrust(114027) algorithm(80) explicitcomposite(5) kem(2) 40 }

pk-MLKEM1024-ECDH-P521-HKDF-SHA384 PUBLIC-KEY ::= 
  pk-CompositeKEM {
    id-MLKEM1024-ECDH-P521-HKDF-SHA384 }

kema-MLKEM1024-ECDH-P521-HKDF-SHA384 KEM-ALGORITHM ::= 
    kema-CompositeKEM{
      id-MLKEM1024-ECDH-P521-HKDF-SHA384, 
      id-MLKEM1024-ECDH-P521-HKDF-SHA384 }

END
